desc: AutoHotkey v2 是一款面向 Windows 的开源脚本语言，提供强大的键盘/鼠标自动化、热键定义及 GUI 创建功能，语法全面升级为基于表达式的现代风格。
tags:
  - Windows
  - 自动化工具
  - 脚本工具
  - 开发
  - GUI
version: unknown
github: AutoHotkey/AutoHotkey
date: "2026-01-21"
