desc: Obsidian Dataview 是一个为 Obsidian 知识库提供的实时索引和查询引擎，支持元数据查询、过滤、排序和分组
tags:
  - Obsidian
  - 知识管理
  - Dataview
  - DQL
  - JavaScript
  - 查询语法
  - 元数据
  - 插件
version: unknown
github: blacksmithgu/obsidian-dataview
date: "2026-01-26"
