desc: GSAP (GreenSock Animation Platform) 是业界领先的JavaScript动画库，为现代网页提供高性能、专业的动画解决方案。支持从简单的属性动画到复杂的时间轴序列，拥有丰富的插件生态系统和完整的工具集。
tags:
  - Web 前端
  - 动画引擎
  - 开发
  - 库 / SDK
version: unknown
github: greensock/GSAP
date: "2025-11-14"
