desc: >-
  Vim
  高度可配置的文本编辑器核心命令与快捷键速查，涵盖基础操作到高级功能的完整指南，实现高效文本编辑。包含模式切换、光标移动、编辑操作、查找替换、宏录制、文本对象、窗口管理、标签操作、缓冲区管理、代码折叠、拼写检查和配置设置等全方位功能。
tags:
  - Linux
  - 编辑器
  - 命令行
version: unknown
github: vim/vim
date: "2025-11-17"
