desc: OpenSpec：面向 AI 编码助手的规格先行工作流与变更管理，一致对齐意图后再实施变更。
tags: ["AI / LLM", "CLI / Terminal", "CLI 工具", "AI 辅助工具", "规范 / 流程", "命令行", "开发"]
version: unknown
github: OAI/OpenAPI-Specification
date: "2025-11-12"
