desc: >-
  LiteLLM 是一个统一的 LLM API 代理服务器，支持 100+ 模型提供商，提供一致的 OpenAI 格式接口。包含完整配置指南，涵盖模型配置、路由负载均衡、缓存系统、安全认证、监控回调、Docker
  部署、性能优化、告警通知等核心功能，以及与 Claude Code、GitHub Copilot、AutoGen 等工具的集成配置。
tags:
  - AI / LLM
  - 代理 / 服务
  - 运维
  - 命令行
version: unknown
github: BerriAI/litellm
date: "2025-11-17"
